### ISSUE TITLE
How do I customize the rotating arrow in sidebar items that have a dropdown?

### ISSUE THREAD

**Issue by denishaskin** [coreui/coreui-free-bootstrap-admin-template#131]
The rotating left arrow seems too small, and is also is weird that the arrow points left when the dropdown is closed.  It is more common that it would point right (at least in l-to-r locales), and then twist to point down when the dropdown is open.

I've hunted through the code but so far I've had no luck figuring out where that is defined.  Suggestions?
<img width="360" alt="coreui_bootstrap_4_admin_template" src="https://cloud.githubusercontent.com/assets/976900/23842555/53c7bef0-0772-11e7-9c4e-92819f853260.png">

**Comment by tjankov** [comment]
It may be too small, a bit, but that is a matter of your own styling. You can adjust that in your own css.

As for the left-pointing arrow, since we are talking about collapsing menu that opens below (as opposed to opening on the right side as popup), I dont think this is wrong.

It indicates that the menu item has collapsed menu.

It's as it is supposed to be.

If you adjust the code for the icon, you can easily change it yourself, though.

**Comment by tjankov** [comment]
I dont think this is an issue.
