### ISSUE TITLE
v2.0.0-beta.0

### ISSUE THREAD

**Issue by mrholek** [coreui/coreui-free-bootstrap-admin-template#356]
We just released first beta of version 2.0.0. We're looking to your feedback

**Comment by mvelosop** [comment]
Hi @mrholek, I'm having a hard time trying to install version 2.0.0.

When running **npm install @coreui/coreui-free-bootstrap-admin-template --save** I get this:
![image](https://user-images.githubusercontent.com/7357806/38379470-b3045bc2-38f8-11e8-8d42-0345b528f81f.png)

And when running **npm install** after cloning the repo, it fails because node_modules is empty. I understand this is an **npm** problem, but just asking in case you've gone through it, because I have tried several solutions from SO, bur none have worked so far.

TIA.

**Comment by mrholek** [comment]
Please try this steps: https://github.com/coreui/coreui-free-bootstrap-admin-template#installation

**Comment by mrholek** [comment]
Please try now. Everything should works.

**Comment by Cristoto** [comment]
I try again and the last problem is solve it.
But now there is a new problem with other URL.
Error: 404 Not Found: @coreui/plugin-chartjs-custom-tooltips@https://registry.npmjs.org/@coreui/plugin-chartjs-custom-tooltips/-/plugin-chartjs-custom-tooltips-0.0.1.tgz

**Comment by Cristoto** [comment]
Now, everything works fine.
Thank you!

**Comment by mvelosop** [comment]
Thanks @mrholek, just as @Cristoto said, it's working now!

Excellent work by the way! congrats!

**Comment by mvelosop** [comment]
And I guess we'll just forget about the **npm install @coreui/coreui-free-bootstrap-admin-template --save** command,  since it is not any more in the readme, right?
