### ISSUE TITLE
Getting to CoreUI v3.0.0

### ISSUE THREAD

**Issue by mrholek** [coreui/coreui-free-bootstrap-admin-template#482]
Hi,

I'm pleased to announce that after several months of development we are ready to share with you first version of CoreUI 3.x. The general plan for CoreUI 3.x development starts with a few alpha releases. Expect another alpha releases this and next month. 

Here you can find the latest version of CoreUI:

- [CoreUI 3 Library](https://github.com/coreui/coreui/tree/v3-next)
- [CoreUI 3 Free Admin Template](https://github.com/coreui/coreui-free-bootstrap-admin-template/tree/v3-next)
- [CoreUI 3 Pro Demo](https://coreui.io/demo/3.0/#main.html)

We are looking forward to your ideas and comments.

**Comment by mentadev** [comment]
For future releases it would be good to include ngx-translate right out the box

**Comment by tabacitu** [comment]
Excellent job on CoreUI, @mrholek . Imho, you've created the best free HTML template for admin panels - _by far_. It even has more features than a lot of _paid_ templates. And the code quality is _definitely_ better than a lot of paid templates 😄 

One question about CoreUI v3-alpha. [I see](https://github.com/coreui/coreui-free-bootstrap-admin-template/compare/v3-next?expand=1#diff-083c69dfc541ea7619485fbf6363443c) one of the major breaking changes is that **all CoreUI class names are now prefixed by ```c-```**. So you have:
```diff
-<ul class="nav navbar-nav d-md-down-none">
+<ul class="c-nav c-header-nav c-d-md-down-none">
-<li class="nav-item px-3"><a class="nav-link" href="#">Dashboard</a></li>
+<li class="c-nav-item c-px-3"><a class="c-nav-link" href="#">Dashboard</a></li>
```

 **Can I ask about the reasoning behind adding a prefix to all class names?** I assume you've done this to avoid conflicts with users' own CSS? Or with Bootstrap itself. But:
- I personally haven't had any classname conflicts when using CoreUI v2 - so I'm wondering if it's a real issue for people; then again, I'm always building _on top_ of CoreUI v2, never bringing it to an existing project;
- if I understand correctly, we'd now have both Bootstrap helper classes, and CoreUI v3 helper classes on page, doing pretty much the same thing - manipulating margin, padding etc; 

I'm asking this because I actually _enjoyed_ that they weren't prefixed:
- I could copy-paste code from the Bootstrap website, and it would just look like CoreUI;
- I could install JS plugins with BS4 design, and they would fit the design well;

It seemed a bit odd to use the same class names as Bootstrap _at first_, and that Bootstrap was basically baked in and overwritten. _But then_ it turned out _very_ practical. Saved me both time and headspace.

It's definitely possible that I'm missing some huge benefit. It's been known to happen 😄 

Thanks! Great job, again.

**Comment by ASKemp** [comment]
Would tend to agree with the above, makes conversion more difficult

**Comment by mentadev** [comment]
I agree with @tabacitu. I'm looking forward for this version and I plan to migrate my sites from V2 to V3 but with this "-c" prefix will make it very hard to migrate. I will have to migrate this -c to every single class :(

**Comment by mrholek** [comment]
@tabacitu @ASKemp @mentadev Thank you for your feedback. We removed all prefixes from Bootstrap components, at this moment only our components have c- prefix.
